[package]
name = "Protocol"
version = "0.0.1"
published-at = "0x0edc00c6e65eb3d4fa369b3b1de6ccbcd11185e027ebb5cc49c8c66c7ce903bd"

[dependencies.Sui]
git = "https://github.com/MystenLabs/sui.git"
subdir = "crates/sui-framework/packages/sui-framework"
rev = "testnet"

[dependencies.Math]
local = "../libs/math"

[dependencies.X]
local = "../libs/x"

[dependencies.Whitelist]
local = "../libs/whitelist"

[dependencies.CoinDecimalsRegistry]
local = "../libs/coin_decimals_registry"

[dependencies.XOracle]
local = "../sui_x_oracle/x_oracle"

[addresses]
protocol = "0x0edc00c6e65eb3d4fa369b3b1de6ccbcd11185e027ebb5cc49c8c66c7ce903bd"
