[package]
name = "Protocol"
version = "0.0.1"
published-at = "0x9682b1cd3f487d60a5d89eab82e81a6f78d6138759cae6e2ca43030752c3f7b5"
testnet-published-at = "0x9682b1cd3f487d60a5d89eab82e81a6f78d6138759cae6e2ca43030752c3f7b5"

[dependencies.Sui]
git = "https://github.com/MystenLabs/sui.git"
subdir = "crates/sui-framework/packages/sui-framework"
rev = "testnet"

[dependencies.Math]
local = "../libs/math"

[dependencies.X]
local = "../libs/x"

[dependencies.Whitelist]
local = "../libs/whitelist"

[dependencies.CoinDecimalsRegistry]
local = "../libs/coin_decimals_registry"

[dependencies.TestCoin]
local = "../test_coin"

[dependencies.XOracle]
local = "../sui_x_oracle/x_oracle"

[addresses]
protocol = "0x9682b1cd3f487d60a5d89eab82e81a6f78d6138759cae6e2ca43030752c3f7b5"

[testnet-addresses]
protocol = "0x9682b1cd3f487d60a5d89eab82e81a6f78d6138759cae6e2ca43030752c3f7b5"
