[package]
name = "Protocol"
version = "0.0.1"

[dependencies.Sui]
git = "https://github.com/MystenLabs/sui.git"
subdir = "crates/sui-framework/packages/sui-framework"
rev = "testnet"

[dependencies.Math]
local = "../math"

[dependencies.X]
local = "../x"

[dependencies.TestCoin]
local = "../test_coin"

[dependencies.Oracle]
local = "../oracle"

[dependencies.Whitelist]
local = "../whitelist"

[dependencies.XOracle]
local = "../../sui-x-oracle/x_oracle"

[addresses]
protocol = "0x0"
