[package]
name = "ProtocolQuery"
version = "0.0.1"
published-at = "0x4c60f64f4ee246eefabf9cf47c176212d5c7851c7c7ef0ca6877f091337fcecc"
testnet-published-at = "0x4c60f64f4ee246eefabf9cf47c176212d5c7851c7c7ef0ca6877f091337fcecc"

[dependencies.Sui]
git = "https://github.com/MystenLabs/sui.git"
subdir = "crates/sui-framework/packages/sui-framework"
rev = "testnet"

[dependencies.Protocol]
local = "../protocol"

[addresses]
protocol_query = "0x4c60f64f4ee246eefabf9cf47c176212d5c7851c7c7ef0ca6877f091337fcecc"

[testnet-addresses]
protocol_query = "0x4c60f64f4ee246eefabf9cf47c176212d5c7851c7c7ef0ca6877f091337fcecc"
