[package]
name = "PythRule"
version = "0.0.1"
published-at = "0x68eaf1b1e7c48d079e6cf8cbcb3d241886839b315778a124115aebeee92592d6"
testnet-published-at = "0x68eaf1b1e7c48d079e6cf8cbcb3d241886839b315778a124115aebeee92592d6"

[dependencies.Sui]
git = "https://github.com/MystenLabs/sui.git"
subdir = "crates/sui-framework/packages/sui-framework"
rev = "mainnet"
override = true

[dependencies.MoveStdlib]
git = "https://github.com/MystenLabs/sui.git"
subdir = "crates/sui-framework/packages/move-stdlib"
rev = "mainnet"
override = true

[dependencies.Pyth]
local = "./vendors/pyth"

[dependencies.XOracle]
local = "../x_oracle"

[addresses]
pyth_rule = "0x68eaf1b1e7c48d079e6cf8cbcb3d241886839b315778a124115aebeee92592d6"

[testnet-addresses]
pyth_rule = "0x68eaf1b1e7c48d079e6cf8cbcb3d241886839b315778a124115aebeee92592d6"
