[package]
name = "ProtocolQuery"
version = "0.0.1"
published-at = "0x9b0c19f38b032a7f38310a596cc16f705acce3bd41aaf8eac2e1b45cbc679ac7"

[dependencies.Sui]
git = "https://github.com/MystenLabs/sui.git"
subdir = "crates/sui-framework/packages/sui-framework"
rev = "testnet"

[dependencies.ScallopProtocol]
local = "../protocol"

[addresses]
protocol_query = "0x9b0c19f38b032a7f38310a596cc16f705acce3bd41aaf8eac2e1b45cbc679ac7"
